#!/bin/bash

./cmakegen-gcc-x64-debug.sh

BUILD_DIR=../build/gcc-x64-debug
pushd $BUILD_DIR

# Run build.
echo "[*] Build is running..."
cmake --build . --config Debug

# Exit
echo "[*] Project build succeeded!"
popd

